### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [DaFXF105/prj-rev-bwfs-dasmoto#6]
Grade: Satisfactory

Summary: Nice job on this project, the final result looks accurate. You used some good techniques and your code was well organized. I created a few issues you should take a look at as they will help you streamline your code. As projects get bigger in size (much bigger) it's going to be important to be efficient. Here's an article with a lot of little tips for improving your code:
http://learn.shayhowe.com/html-css/writing-your-best-code/

**Comment by DaFXF105** [comment]
Thanks for the feedback, it's very useful. I will try and incorporate the techniques you have given me. 

David
